apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: springboot 
spec:
  replicas: 3
template:
    metadata:
      name: springboot
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot 
        image: ganeshaws/springboot:v1
        ports:
        - containerPort: 8080

